### PR TITLE
Quick fix for #186

### PR DESCRIPTION
**Pull request by kirill-konshin**

### CODE REVIEW

**Comment by mastilver** [comment]
please add a test also should probably target `next`

**Comment by kirill-konshin** [comment]
Changed base to next. Can you suggest any existing test that I can take as example?

**Comment by mastilver** [comment]
I think https://github.com/danethurber/webpack-manifest-plugin/blob/5715c07748a80dae583074304e306534eac1896a/spec/plugin.spec.js#L68 is a good place to start

Could you rebase on `next`, tests picking the right configuration

**Comment by kirill-konshin** [comment]
The problem is that I have no idea how to force plugin in the state when `asset.chunks` is not defined.

**Comment by mastilver** [comment]
Thank you, I just wanted to confirm it was an actual issue and it just happens that master started failing on this

**Pull request merged**
