### PR TITLE
fix: use multiple instances at the same time 

### LINKED ISSUE #100: having multiple instances of this plugin seems to prevent webpack from emitting any files other than the manifests
2.0.0-rc.1

```
    new ManifestPlugin({
        fileName: 'manifest-android.json',
        filter: (file)=>!file.path.match(/\.mp3$|\.map$/),
    }),
    new ManifestPlugin({
        fileName: 'manifest-ios.json',
        filter: (file)=>!file.path.match(/\.ogg$|\.map$/),
    })
```

with only one ManifestPlugin everything works. with two, no assets are emitted by webpack, except the two manifest jsons.

### PR DESCRIPTION
**Pull request by mastilver**
closes #100

### CODE REVIEW

**Comment by deguif** [comment]
Regarding #100 discussion that means that's the multi instance solution that was chosen.

**Comment by mastilver** [comment]
@deguif Yeah, I really wasn't sure what was the right solution..., I think this is the most natural for the user, I hope it doesn't introduce any bugs...

**Comment by deguif** [comment]
@mastilver Yes, I totally agree. I find it better too. But from the discussion I was ready to play with an array of config.

**Comment by deguif** [comment]
Is there any reason why it doesn't get merged?

**Comment by deguif** [comment]
Any news about this PR?

**Pull request merged**
